logo: "https://github.com/evanca/evanca.github.io/blob/master/logo.png?raw=true"
description: > # newlines will be ignored in this theme, using <br> instead
  Data Analyst (SQL / Python / R / Tableau) | Android Developer (Java / Android Studio IDE) | Executive Director in a Promotional Merchandise Company
  <br><br>
  Data Analyst Nanodegree (Udacity Bertelsmann Data Science Scholarship)
  // Android Basics Nanodegree (Udacity Google Developer Nanodegree Scholarship)
  // Bachelor in Business Studies (BBS)
  <br><br>
  <a href="https://www.linkedin.com/in/i-am-naveen-m-j/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: 
